Repository snippet-labs/SCRIPTLAB, pull requests merged in 2025-03, with the labels that each got.

#6 page(footer-redesigned): footer redesigned and developed.
  src/components/CodeEditor/CodeEditor.jsx
  src/components/Footer/Footer.jsx
  src/components/Layout/Layout.jsx
  src/index.css
  src/pages/ErrorPage.jsx
  src/pages/Navigation/Contact.jsx
  src/pages/Navigation/FlashCardsPage.jsx
  src/pages/Navigation/HomePage.jsx
  src/pages/Template/Template.jsx
  src/pages/TermsAndConditions.jsx
  src/pages/UnderDevelopment.jsx
  src/utils/Pagination/Pagination.jsx
Labels: new feature, enhancement, ready to merge, attention needed

#9 page(footer): universal spacing
  src/components/CodeEditor/CodeEditor.jsx
  src/components/Footer/Footer.jsx
  src/components/Layout/Layout.jsx
  src/index.css
  src/pages/ErrorPage.jsx
  src/pages/Navigation/Contact.jsx
  src/pages/Template/Template.jsx
  src/pages/UnderDevelopment.jsx
Labels: enhancement, ready to merge

#10 Layout changed, optimized for scrollable code snippets
  bun.lockb
  package.json
  src/App.jsx
  src/components/CodeEditor/CodeEditor.jsx
  src/components/Footer/Footer.jsx
  src/components/Layout/Layout.jsx
  src/index.css
  src/pages/Navigation/HomePage/CodeSnippet.js
  src/pages/Navigation/HomePage/HomePage.jsx
  src/pages/Sidebar/InputAndOutput/CodeSnippet.js
  src/pages/Sidebar/InputAndOutput/InputAndOutput.jsx
  src/pages/Sidebar/VariableAndDataTypes/CodeSnippet.js
  src/pages/Template/Template.jsx
  src/utils/Button/Button.jsx
  src/utils/CodeHighlighter/CodeHighlighter.jsx
  src/utils/Console/Console.jsx
Labels: new feature, enhancement, ready to merge, attention needed, fixed

#11 page(input-output): Completed
  src/index.css
  src/pages/Navigation/HomePage/HomePage.jsx
  src/pages/Sidebar/InputAndOutput/CodeSnippet.js
  src/pages/Sidebar/InputAndOutput/InputAndOutput.jsx
  src/utils/Chapter/Chapter.jsx
  src/utils/Console/Console.jsx
  src/utils/Pagination/Pagination.jsx
Labels: new feature, attention needed

#12 Page(Introduction) : Completed
  src/components/Layout/Layout.jsx
  src/pages/Sidebar/Introduction.jsx
  src/utils/InfoModal/InfoModal.jsx
Labels: enhancement, ready to merge, attention needed

#14 feature(code-editor): Onpage javascript code-editor
  bun.lockb
  contribution.md
  package.json
  src/components/CodeEditor/CodeEditor.jsx
  src/components/CodeEditor/CodeSnippet.js
  src/components/Layout/Layout.jsx
  src/utils/CodeHighlighter/CodeHighlighter.jsx
Labels: enhancement, attention needed, fixed

#18 optimize(application): Code splitting
  src/components/Layout/Layout.jsx
  src/pages/ErrorPage.jsx
  src/pages/Navigation/Contact.jsx
Labels: enhancement, ready to merge

#19 validation(prop-types): added prop validation
  bun.lockb
  package.json
  src/components/CodeEditor/CodeEditor.jsx
  src/pages/ErrorPage.jsx
  src/pages/Navigation/Contact.jsx
  src/pages/Navigation/HomePage/HomePage.jsx
  src/pages/Sidebar/InputAndOutput/InputAndOutput.jsx
  src/pages/Template/Template.jsx
  src/pages/TermsAndConditions.jsx
  src/pages/UnderDevelopment.jsx
  src/utils/Button/Button.jsx
  src/utils/Chapter/Chapter.jsx
  src/utils/CodeHighlighter/CodeHighlighter.jsx
  src/utils/Console/Console.jsx
  src/utils/InfoModal/InfoModal.jsx
  src/utils/Loader/Loader.jsx
  src/utils/Pagination/Pagination.jsx
Labels: enhancement, ready to merge, attention needed, fixed
